{
    'name': 'ACC Users',
    'version': '0.1',
    'Summary': ' ACC Users',
    'author': 'Prashanna',
    'description': 'ACC Users',
    'website': '',
    'category': 'User',
    'data': [
    'groups.xml',
    # 'ir.model.access.csv',
    'acc_res_config_settings_view.xml',
    'acc_report_template.xml',
    'acc_users_view.xml',
    'acc_company_view.xml',
    'acc_bank_view.xml',
    'acc_partner_view.xml',
    # 'wizard/acc_temp_partner_view.xml',
    # 'acc_mail_view.xml',
    ],
    'depends': ['base','account','mail','mail_bot','base_address_city','product','sale'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
