{
    'name': 'ACC Masters',
    'version': '0.1',
    'Summary': ' ACC Masters',
    'author': 'Prashanna',
    'description': 'ACC Masters',
    'website': '',
    'category': 'Masters',
    'data': [
    'ir.model.access.csv',
    # 'acc_location_master_view.xml',
    'acc_followup_mail_view.xml',
    'acc_vehicle_master_view.xml',
    'acc_quote_validity_view.xml',
    'acc_source_enquiry.xml',
    'acc_delivery_period.xml',
    'acc_availability_period.xml',
    'acc_delivery_terms.xml',
    'acc_manufacturer_view.xml',
    'acc_sales_commission_view.xml',
    'acc_prod_sub_category_view.xml',
    'data/acc_master_data.xml',
    'employee_commission_master_view.xml',
    ],
    'depends': ['base','mail','acc_users','account','product'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
