{
    'name': 'ACC Stock',
    'version': '0.1',
    'Summary': ' ACC Stock',
    'author': 'Prashanna',
    'description': 'ACC Stock',
    'website': '',
    'category': 'stock',
    'data': [
    # 'security_view.xml',
    'ir.model.access.csv',
    'acc_stock_config_settings_view.xml',
    'reports/acc_picking_report_pdf.xml',
    'reports/acc_picking_report_view.xml',
    'reports/acc_consignment_report_pdf.xml',
    'reports/acc_consignment_report_view.xml',
    'reports/acc_consignment_detail_report_pdf.xml',
    'reports/acc_delivery_slip_report_pdf.xml',
    'reports/acc_consignment_detail_report_view.xml',
    'reports/acc_packing_list_report_pdf.xml',
    'reports/acc_top_selling_products_report_view.xml',
    'reports/top_selling_products_report_wizard_view.xml',
    'reports/product_profit_report_view.xml',
    'reports/product_profit_report_wizard_view.xml',
    'picking_invoice_wizard.xml',
    'acc_product_view.xml',
    'acc_consignment_view.xml',
    'acc_picking_view.xml',
    'acc_packing_list_view.xml',
    ],
    'depends': ['base','stock','hr','sale_stock','sale','acc_masters','purchase','point_of_sale'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
